<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ListMenusTableSeeder extends Seeder
{
    /**
     * Auto generated seeder file.
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('list_menus')->delete();
        
        \DB::table('list_menus')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/executive',
                'path' => 'Modules/Executive/Dashboard',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            1 => 
            array (
                'id' => 2,
                'name' => 'User Management',
                'icon' => 'ri-team-fill ',
                'route' => '/executive/users',
                'path' => 'Modules/Executive/Users',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            2 => 
            array (
                'id' => 3,
                'name' => 'Role Management',
                'icon' => 'ri-shield-check-line',
                'route' => '/executive/roles',
                'path' => 'Modules/Executive/Roles',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            3 => 
            array (
                'id' => 4,
                'name' => 'Menu Management',
                'icon' => 'ri-list-check',
                'route' => '/executive/menus',
                'path' => 'Modules/Executive/Menus',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            4 => 
            array (
                'id' => 5,
                'name' => 'Authentication Logs',
                'icon' => 'ri-time-fill',
                'route' => '/executive/authentications',
                'path' => 'Modules/Executive/Authentications',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 5,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            5 => 
            array (
                'id' => 6,
                'name' => 'Activity Logs',
                'icon' => 'ri-history-line',
                'route' => '/executive/activities',
                'path' => 'Modules/Executive/Activities',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 6,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            6 => 
            array (
                'id' => 7,
                'name' => 'Backup and Restore',
                'icon' => 'ri-server-line ',
                'route' => '/executive/backups',
                'path' => 'Modules/Executive/Backups',
                'group' => 'Menu',
                'module' => 'Executive',
                'order' => 7,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            7 => 
            array (
                'id' => 8,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/references',
                'path' => 'Modules/References/Dashboard',
                'group' => 'Menu',
                'module' => 'Reference',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            8 => 
            array (
                'id' => 9,
                'name' => 'Laboratories',
                'icon' => 'ri-hotel-fill',
                'route' => '/references/laboratories',
                'path' => 'Modules/References/Laboratories',
                'group' => 'Menu',
                'module' => 'Reference',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            9 => 
            array (
                'id' => 10,
                'name' => 'Discounts',
                'icon' => 'ri-hand-coin-fill',
                'route' => '/references/discounts',
                'path' => 'Modules/References/Discounts',
                'group' => 'Menu',
                'module' => 'Reference',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            10 => 
            array (
                'id' => 11,
                'name' => 'Industries',
                'icon' => 'ri-bill-fill',
                'route' => '/references/industries',
                'path' => 'Modules/References/Industries',
                'group' => 'Menu',
                'module' => 'Reference',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            11 => 
            array (
                'id' => 12,
                'name' => 'Statuses',
                'icon' => 'ri-pages-fill',
                'route' => '/references/statuses',
                'path' => 'Modules/References/Statuses',
                'group' => 'Menu',
                'module' => 'Reference',
                'order' => 5,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            12 => 
            array (
                'id' => 13,
                'name' => 'Locations',
                'icon' => 'ri-earth-fill',
                'route' => NULL,
                'path' => 'Modules/References/Locations',
                'group' => 'List',
                'module' => 'Reference',
                'order' => 6,
                'has_child' => 1,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            13 => 
            array (
                'id' => 14,
                'name' => 'Regions',
                'icon' => NULL,
                'route' => '/references/regions',
                'path' => '/references/regions',
                'group' => 'Locations',
                'module' => 'Reference',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            14 => 
            array (
                'id' => 15,
                'name' => 'Provinces',
                'icon' => NULL,
                'route' => '/references/provinces',
                'path' => '/references/provinces',
                'group' => 'Locations',
                'module' => 'Reference',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            15 => 
            array (
                'id' => 16,
                'name' => 'Municipalities',
                'icon' => NULL,
                'route' => '/references/municipalities',
                'path' => '/references/municipalities',
                'group' => 'Locations',
                'module' => 'Reference',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            16 => 
            array (
                'id' => 17,
                'name' => 'Barangays',
                'icon' => NULL,
                'route' => '/references/barangays',
                'path' => '/references/barangays',
                'group' => 'Locations',
                'module' => 'Reference',
                'order' => 4,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            17 => 
            array (
                'id' => 18,
                'name' => 'Dropdowns',
                'icon' => 'ri-list-unordered',
                'route' => NULL,
                'path' => 'Modules/References/Dropdowns',
                'group' => 'List',
                'module' => 'Reference',
                'order' => 7,
                'has_child' => 1,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            18 => 
            array (
                'id' => 19,
                'name' => 'Agency Type',
                'icon' => NULL,
                'route' => '/references/schools',
                'path' => '/references/schools',
                'group' => 'Dropdowns',
                'module' => 'Reference',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            19 => 
            array (
                'id' => 20,
                'name' => 'Discount',
                'icon' => NULL,
                'route' => '/references/courses',
                'path' => '/references/courses',
                'group' => 'Dropdowns',
                'module' => 'Reference',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            20 => 
            array (
                'id' => 21,
                'name' => 'Payment Method',
                'icon' => NULL,
                'route' => '/references/categories',
                'path' => '/references/categories',
                'group' => 'Dropdowns',
                'module' => 'Reference',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 0,
                'is_active' => 1,
            ),
            21 => 
            array (
                'id' => 43,
                'name' => 'Dashboard',
                'icon' => 'ri-apps-line',
                'route' => '/dashboard',
                'path' => 'Modules/Operation/Dashboard',
                'group' => 'Menu',
                'module' => 'Operation',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            22 => 
            array (
                'id' => 44,
                'name' => 'Customers',
                'icon' => 'ri-team-fill',
                'route' => '/customers',
                'path' => 'Modules/Operation/Customers',
                'group' => 'Menu1',
                'module' => 'Operation',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            23 => 
            array (
                'id' => 45,
                'name' => 'Quotations',
                'icon' => 'ri-price-tag-3-fill',
                'route' => '/quotations',
                'path' => 'Modules/Operation/Quotations',
                'group' => 'Menu2',
                'module' => 'Operation',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            24 => 
            array (
                'id' => 46,
                'name' => 'TS Requests',
                'icon' => 'ri-hand-coin-fill',
                'route' => '/tsrs',
                'path' => 'Modules/Operation/Tsrs',
                'group' => 'Menu2',
                'module' => 'Operation',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            25 => 
            array (
                'id' => 47,
                'name' => 'Reports',
                'icon' => 'ri-file-text-fill',
                'route' => '/reports',
                'path' => 'Modules/Operation/Reports',
                'group' => 'Menu3',
                'module' => 'Operation',
                'order' => 1,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            26 => 
            array (
                'id' => 48,
                'name' => 'Calender',
                'icon' => 'ri-calendar-fill',
                'route' => '/calendars',
                'path' => 'Modules/Operation/Calendars',
                'group' => 'Menu2',
                'module' => 'Operation',
                'order' => 3,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
            27 => 
            array (
                'id' => 49,
                'name' => 'Test Services',
                'icon' => 'ri-flask-fill',
                'route' => '/services',
                'path' => 'Modules/Operation/Services',
                'group' => 'Menu1',
                'module' => 'Operation',
                'order' => 2,
                'has_child' => 0,
                'is_mother' => 1,
                'is_active' => 1,
            ),
        ));

        
    }
}